class RegistrationTestData:
    email = "anything@8pyk8lj3.mailosaur.net"
    username = "umer"
    surname = "ehsan"
    password = "Code@4180"
    address = "Lahore"
    zipcode = "54000"
    street_address = "1st street in lahore"
    compnay_name_search = "Code"
    minmum_project_price = "10000"
    freelance_company = "Code"