from selenium.webdriver.common.by import By
class busniness_registrationLocators:
    business_basic_option = (By.XPATH, "//label[3]")
    business_basic_dropdown = (By.XPATH, "//input[@id=':r1:']")
    add_business_select = (By.XPATH, "//p[@class='MuiTypography-root MuiTypography-body1 body1 mui-1w6h4uc']")
    email_input_field = (By.XPATH, "//input[@name='businessEmail']")
    company_name_input_field = (By.XPATH, "//input[@name='company']")
    business_division_name = (By.XPATH, "//input[@name='unit']")
    business_url = (By.XPATH, "//input[@name='businessUrl']")
    continue_button = (By.XPATH, "//div[@class='MuiStack-root add-identity-footer mui-n4rzf0']//button[@type='submit'][normalize-space()='Continue']")
    country_dropdown = (By.XPATH, "//input[@id=':r5:']")
    state_dropdown = (By.XPATH, "//div[@id='mui-component-select-province']")
    state_dropdown_option = (By.XPATH, "//li[contains(text(),'Badakhshān (AF-BDS)')]")
    city_input_field = (By.XPATH, "//input[@name='city']")
    postalcode_input_field = (By.NAME, "addressZip")
    street_address_input_field = (By.NAME, "address1")
    continue_button_1 = (By.ID, ':r4:')
    revenue_input_field = (By.NAME, "revenue")
    company_size_input_field = (By.NAME, "companySize")
    ownership_type_dropdown = (By.ID, "mui-component-select-ownershipType")
    ownership_type_option = (By.XPATH, "//li[normalize-space()='Public']")
    entity_type_dropdown = (By.XPATH, "//div[@id='mui-component-select-entityType']")
    entity_type_option = (By.XPATH, "//li[normalize-space()='Parent']")
    headquarter_dropdown = (By.XPATH, "//div[@id='mui-component-select-headquarter']")
    headquarter_dropdown_option = (By.XPATH, "//li[normalize-space()='Yes']")
    scroll_element = (By.XPATH, "//div[@class='MuiStack-root add-identity-fields mui-j7qwjs']")
    founded_year_dropdown = (By.XPATH, '//div[@id=\'mui-component-select-founded\']')
    founded_year_option = (By.XPATH, "//li[normalize-space()='2023']")
    continue_button_2 = (By.XPATH, "(//button[@type='submit'][normalize-space()='Continue'])[2]")
    browse_button = (By.XPATH, "//button[normalize-space()='Browse']")
    primary_industry_parent_option = (By.XPATH, "//p[normalize-space()='Professional, Scientific, and Technical Services']")
    primary_industry_child_option = (By.XPATH, "//p[normalize-space()='Legal Services']")
    primary_industry_child_option_1 = (By.XPATH, "//span[normalize-space()='Offices of Lawyers']")
    primary_industry_child_option_2 = (By.XPATH, "/html[1]/body[1]/div[4]/div[3]/div[1]/div[2]/div[2]/div[3]/ul[1]/li[1]/ul[1]/div[1]/div[1]/li[1]/ul[1]/div[1]/div[1]/li[1]/ul[1]/div[1]/div[1]/li[1]/div[1]/div[2]/label[1]/span[2]")
    done_button = (By.XPATH, "//button[normalize-space()='Done']")
    continue_button_3 = (By.XPATH, "(//button[@type='submit'][normalize-space()='Continue'])[2]")
    secondary_industry_parent = (By.XPATH, "//p[normalize-space()='Agriculture, Forestry, Fishing and Hunting']")
    secondary_industry_child = (By.XPATH, "//p[normalize-space()='Oilseed and Grain Farming']")
    secondary_industry_child_1 = (By.XPATH, "//span[normalize-space()='Soybean Farming']")
    secondary_industry_child_2 = (By.XPATH, "//span[@class='MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label mui-1w6h4uc']")
    add_business_button = (By.XPATH, "//button[normalize-space()='Add Business']")
    continue_button_4 = (By.XPATH, "//button[normalize-space()='Continue']")
    same_as_previous_checkbox = (By.XPATH, "//span[normalize-space()='Same as previously added business']")
    create_basic_business_account_button = (By.XPATH, "//button[@id=':r14:']")



