from selenium.webdriver.common.by import By
class busniness_registrationLocators:
    business_basic_option = (By.XPATH, "//label[3]")
    business_basic_dropdown = (By.XPATH, "//input[@id=':r1:']")
    add_business_select = (By.ID, "btn-add-business")
    email_input_field = (By.ID, "business-email']")
    company_name_input_field = (By.ID, "business-name")
    business_division_name = (By.ID, "business-unit-name")
    business_url = (By.ID, "business-name")
    continue_button = (By.ID, "btn-continue")
    country_dropdown = (By.XPATH, "//input[@id=':r5:']")
    state_dropdown = (By.XPATH, "//div[@id='mui-component-select-province']")
    state_dropdown_option = (By.XPATH, "//li[contains(text(),'Badakhshān (AF-BDS)')]")
    city_input_field = (By.XPATH, "//input[@name='city']")
    postalcode_input_field = (By.NAME, "addressZip")
    street_address_input_field = (By.NAME, "address")
    revenue_input_field = (By.ID, "revenue")
    company_size_input_field = (By.ID, "company-size")
    ownership_type_dropdown = (By.ID, "mui-component-select-ownershipType")
    ownership_type_option = (By.XPATH, "//li[normalize-space()='Public']")
    entity_type_dropdown = (By.XPATH, "//div[@id='mui-component-select-entityType']")
    entity_type_option = (By.XPATH, "//li[normalize-space()='Parent']")
    headquarter_dropdown = (By.XPATH, "//div[@id='mui-component-select-headquarter']")
    headquarter_dropdown_option = (By.XPATH, "//li[normalize-space()='Yes']")
    scroll_element = (By.XPATH, "//div[@class='MuiStack-root add-identity-fields mui-j7qwjs']")
    founded_year_dropdown = (By.XPATH, '//div[@id=\'mui-component-select-founded\']')
    founded_year_option = (By.XPATH, "//li[normalize-space()='2023']")
    browse_button = (By.ID, "btn-browse")
    primary_industry_parent_option = (By.XPATH, "//p[normalize-space()='Professional, Scientific, and Technical Services']")
    primary_industry_child_option = (By.XPATH, "//p[normalize-space()='Legal Services']")
    primary_industry_child_option_1 = (By.XPATH, "//span[normalize-space()='Offices of Lawyers']")
    primary_industry_child_option_2 = (By.XPATH, "/html[1]/body[1]/div[4]/div[3]/div[1]/div[2]/div[2]/div[3]/ul[1]/li[1]/ul[1]/div[1]/div[1]/li[1]/ul[1]/div[1]/div[1]/li[1]/ul[1]/div[1]/div[1]/li[1]/div[1]/div[2]/label[1]/span[2]")
    done_button = (By.ID, "btn-done")
    secondary_industry_parent = (By.XPATH, "//p[normalize-space()='Agriculture, Forestry, Fishing and Hunting']")
    secondary_industry_child = (By.XPATH, "//p[normalize-space()='Oilseed and Grain Farming']")
    secondary_industry_child_1 = (By.XPATH, "//span[normalize-space()='Soybean Farming']")
    secondary_industry_child_2 = (By.XPATH, "//span[@class='MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label mui-1w6h4uc']")
    add_business_button = (By.ID, "btn-add-business")
    same_as_previous_checkbox = (By.XPATH, "//span[normalize-space()='Same as previously added business']")





