
from selenium.webdriver.common.by import By
class profileLocators:
    viewProfile = (By.ID, "btnViewYourProfile")
    editButton = (By.XPATH, "//button[normalize-space()='Edit']")
    previewButton = (By.XPATH, "//button[normalize-space()='Preview']")
    tagLine = (By.NAME, "tagline")
    aboutMe = (By.NAME, "aboutMe")
    phoneNumber = (By.XPATH, "//input[@placeholder='1 (702) 123-4567']")
    webSiteInput = (By.NAME, "websiteUrl")
    facebookInput = (By.NAME, "facebookUrl")
    twitterInput = (By.NAME, "twitterUrl")
    instagramInput = (By.NAME, "instagramUrl")
    snapchatInput = (By.NAME, "snapChatUrl")
    linkedinInput = (By.NAME, "linkedInUrl")
    saveBtn = (By.XPATH, "(//button[normalize-space()='Save'])[1]")
    resumeTab = (By.XPATH, "(//button[normalize-space()='Resume'])[1]")
    addExperienceButton = (By.XPATH, "//button[normalize-space()='Add Experience']")
    jobTitleDropdown = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/input[1]")
    jobTitleOption = (By.XPATH, "/html[1]/body[1]/div[6]/div[1]/ul[1]/li[1]")
    employerInput = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[2]/div[1]/div[1]/input[1]")
    employerInputOption = (By.XPATH, "(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary mui-1bhfyc0'][normalize-space()='Code District'])[1]")
    startDate = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[4]/div[1]/div[1]/input[1]")
    startDateOption = (By.XPATH, "//button[normalize-space()='13']")
    currentlyCheckbox = (By.NAME, "currently")
    description = (By.NAME, "jobDescription")
    addExperienceButtonPopup = (By.XPATH, "//button[@type='submit'][normalize-space()='Add Experience']")
    addEducationButton = (By.XPATH, "//button[normalize-space()='Add Education']")
    fieldOfStudy = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/input[1]")
    fieldOfStudyOption = (By.XPATH, "/html[1]/body[1]/div[6]/div[1]/ul[1]/li[1]")
    edInstitute = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[2]/div[1]/div[1]/input[1]")
    addEducationButtonPop = (By.XPATH, "(//button[@type='submit'][normalize-space()='Add Education'])[1]")
    addSkillsButton = (By.XPATH, "//button[normalize-space()='Add Skills']")
    enterSkills = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/input[1]")
    skillOption = (By.XPATH, "/html[1]/body[1]/div[6]/div[1]/ul[1]/li[1]")
    addSkill = (By.XPATH, "//button[@class='MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeSmall MuiButton-outlinedSizeSmall MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeSmall MuiButton-outlinedSizeSmall btn-email mui-7jyovo']//*[name()='svg']")
    doneButton = (By.XPATH, "//button[normalize-space()='Done']")
    addPersonalHonoorsButton = (By.XPATH, "//button[normalize-space()='Add Skills']")
    honorDate = (By.CLASS_NAME, "MuiInputBase-input MuiInput-input MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd mui-1ev6tyo")
    certificateName = (By.XPATH, "//input[@name='certificationName']")
    addWorkPublishButton = (By.XPATH, "//button[normalize-space()='Add works published']")
    workPublishDate = (By.XPATH, "/html[1]/body[1]/div[5]/div[3]/div[1]/div[2]/form[1]/div[1]/div[1]/input[1]")
    certificateField = (By.NAME, "certificationName")
    workPublishDateOption = (By.XPATH, "//button[normalize-space()='2']")
    titleField = (By.NAME, "title")
    authorField = (By.NAME, "authors")
    exitPreview = (By.XPATH, "//button[normalize-space()='Exit Preview']")
    urlInput = (By.NAME, "url")
    manageReference = (By.XPATH, "//button[normalize-space()='Manage Professional Preferences']")
    inviteButton = (By.XPATH, "//button[normalize-space()='Invite new']")
    markMember = (By.XPATH, "(//input[@type='checkbox'])[2]")
    inviteSelected = (By.XPATH, "//button[normalize-space()='Invite selected']")



